package com.app.resources.entities;
// Generated Sep 16, 2020 12:00:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblPerson generated by hbm2java
 */
@Entity
public class TblPerson implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)

    private int personId;
    private String firstName;
    private String middleName;
    private String lastName;
    private Integer age;

    public TblPerson() {
    }

    public TblPerson(int personId) {
        this.personId = personId;
    }

    public TblPerson(String firstName, String middleName, String lastName, Integer age) {
        this.personId = personId;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.age = age;
    }

    public int getPersonId() {
        return this.personId;
    }

    public void setPersonId(int personId) {
        this.personId = personId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

}
